### ISSUE TITLE
Unexpected string in JSON at position 11

### ISSUE THREAD

**Issue by D48utters** [BitQuote/AwesomeBot#172]
When I try and execute node bot.js it tells me there was a unexpected string in auth,json position 11 and i don't know what to do with that. Any help?

**Comment by D48utters** [comment]
$ node bot.js
SyntaxError: C:\Users\Butters\Documents\AwesomeBot-3.4\auth.json: Unexpected string in JSON at position 11
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:573:27)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Butters\Documents\AwesomeBot-3.4\bot.js:6:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
Exiting...

This is what it says

**Comment by Kays** [comment]
As stated in the wiki, the AwesomeBot team does not provide help regarding this matter.
