### ISSUE TITLE
Reconnect issue [closed]

### ISSUE THREAD

**Issue by iluwQaa** [BitQuote/AwesomeBot#187]
```
[2016-09-30 04:39:02 UTC] [INFO] [General] Started *** v3.4.3
Error: Invalid session
    at WebSocket.websocket.onclose (/***t/node_modules/discord.js/lib/Client/InternalClient.js:93:1566)
    at WebSocket.onClose (/***/node_modules/ws/lib/WebSocket.js:446:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at WebSocket.cleanupWebsocketResources (/***/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:85:20)
    at TLSSocket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[2016-09-30 04:39:04 UTC] [ERROR] [General] Something went seriously wrong: Error: Invalid session

```
node -v v5.12.0

Linux 4.4.0-38-generic #57~14.04.1-Ubuntu SMP x86_64 GNU/Linux

**Comment by GilbertGobbels** [comment]
Go to https://discord.gg/6369r for more info about self-hosting, the answer should be there!
