### ISSUE TITLE
stats[svr.id].members[usr.id].strikes.push is not a function

### ISSUE THREAD

**Issue by JLBP** [BitQuote/AwesomeBot#21]
Error happens every time a admin is trying to strike a user via the admin page.

`
TypeError: stats[svr.id].members[usr.id].strikes.push is not a function
    at parseAdminConfig (/Bots/AwesomeBot/start.js:3464:67)
    at /Bots/AwesomeBot/start.js:1948:21
    at Layer.handle [as handle_request] (/Bots/AwesomeBot/node_modules/express/lib/router/layer.js:95:5)
    at next (/Bots/AwesomeBot/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Bots/AwesomeBot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Bots/AwesomeBot/node_modules/express/lib/router/layer.js:95:5)
    at /Bots/AwesomeBot/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:330:12)
    at next (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Bots/AwesomeBot/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Bots/AwesomeBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:312:13)
    at /Bots/AwesomeBot/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:330:12)
    at next (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Bots/AwesomeBot/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Bots/AwesomeBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:312:13)
    at /Bots/AwesomeBot/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:330:12)
    at next (/Bots/AwesomeBot/node_modules/express/lib/router/index.js:271:10)
    at /Bots/AwesomeBot/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Bots/AwesomeBot/node_modules/raw-body/index.js:262:16)
    at done (/Bots/AwesomeBot/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/Bots/AwesomeBot/node_modules/raw-body/index.js:308:7)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
`

**Comment by BitQuote** [comment]
Are you on v3.3.8? If so, you need to clear your stats file or run a script to make the strikes property for each member an array.

**Comment by JLBP** [comment]
Just cleared the stats file and still receiving the same error, but upon start up the bot. (Either running on a fresh clone or from the bot I updated)

`
\start.js:2996
                if(!stats[bot.servers[i].id].members[bot.servers[i].members[j].id]) {
                                            ^

TypeError: Cannot read property 'members' of undefined
    at clearStatCounter (H:\AwesomeBot-3.3.7p1\start.js:2996:45)
    at Client.<anonymous> (H:\AwesomeBot-3.3.7p1\start.js:1584:5)
    at emitNone (events.js:80:13)
    at Client.emit (events.js:179:7)
    at InternalClient.checkReady (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\lib\Client\InternalClient.js:439:17)
    at WebSocket.websocket.onmessage (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\lib\Client\InternalClient.js:2167:14)
    at WebSocket.onMessage (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:841:10)
    at H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:371:5)
    at H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.1.finish (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:541:12)
    at Receiver.expectHandler (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:499:31)
    at Receiver.add (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:103:24)
    at TLSSocket.realHandler (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:523:20)
`

**Comment by BitQuote** [comment]
Alright, you found a bug. It'll be fixed later today in the v3.3.9 branch.




On Thu, Apr 14, 2016 at 10:51 AM -0700, "JLBP" <notifications@github.com> wrote:





Just cleared the stats file and still receiving the same error, but upon start up the bot. (Either running on a fresh clone or from the bot I updated)

`
\start.js:2996
                if(!stats[bot.servers[i].id].members[bot.servers[i].members[j].id]) {
                                            ^

TypeError: Cannot read property 'members' of undefined
    at clearStatCounter (H:\AwesomeBot-3.3.7p1\start.js:2996:45)
    at Client.<anonymous> (H:\AwesomeBot-3.3.7p1\start.js:1584:5)
    at emitNone (events.js:80:13)
    at Client.emit (events.js:179:7)
    at InternalClient.checkReady (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\lib\Client\InternalClient.js:439:17)
    at WebSocket.websocket.onmessage (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\lib\Client\InternalClient.js:2167:14)
    at WebSocket.onMessage (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:841:10)
    at H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:371:5)
    at H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.1.finish (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:541:12)
    at Receiver.expectHandler (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:499:31)
    at Receiver.add (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\Receiver.js:103:24)
    at TLSSocket.realHandler (H:\AwesomeBot-3.3.7p1\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:523:20)
`

---

**Comment by JLBP** [comment]
yeah tried clearing out stats, same error but happened on startup and same with a fresh copy. and thats great :)

**Comment by BitQuote** [comment]
For now you can restore your stats file and run a simple script to make the `strikes` property for each member an empty array. The fix will be pushed later today, and v3.3.9 will be released to stable sometime in the next few days.

**Comment by BitQuote** [comment]
Fixed in v3.3.9!
