### ISSUE TITLE
"Wiki is not a function"

### ISSUE THREAD

**Issue by Corgi** [BitQuote/AwesomeBot#36]
Bot is crashing when I attempt to use the `wiki` command, with the following error:

[2016-05-29 03:35:50 UTC] [INFO] [The Terrible Secret of Teufort, botground] Treating '@PeriBot#9388 wiki peridot' from Corgi! as a command
TypeError: Wiki is not a function
    at Object.commands.wiki.process (/Users/Pemm/peribot/start.js:1039:13)
    at messageHandler (/Users/Pemm/peribot/start.js:2919:17)
    at Domain.<anonymous> (/Users/Pemm/peribot/start.js:2445:9)
    at Domain.run (domain.js:228:14)
    at Client.<anonymous> (/Users/Pemm/peribot/start.js:2444:12)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (/Users/Pemm/peribot/node_modules/discord.js/lib/Client/InternalClient.js:1822:16)
    at WebSocket.onMessage (/Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/Pemm/peribot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:347:3)
[2016-05-29 03:35:50 UTC] [ERROR] [General] Something went seriously wrong: TypeError: Wiki is not a function

Using build 3.3.20p6.

**Comment by tinytaco8** [comment]
Wiki is broken in current release. Will be fixed in the next update.
